"""initial schema

Revision ID: 92e90796459c
Revises:
Create Date: 2026-08-04 19:52:37.578654
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "92e90796459c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "agents",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "revoked", name="agentstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("pairing_token_hash", sa.String(length=64), nullable=True),
        sa.Column("pairing_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("api_key_hash", sa.String(length=64), nullable=True),
        sa.Column("api_key_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("instance_id", sa.String(length=255), nullable=True),
        sa.Column("software_version", sa.String(length=100), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_agents_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_index(op.f("ix_agents_api_key_hash"), "agents", ["api_key_hash"], unique=True)
    op.create_index(op.f("ix_agents_owner_id"), "agents", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_agents_pairing_token_hash"), "agents", ["pairing_token_hash"], unique=True
    )
    op.create_table(
        "payment_methods",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", name="paymentmethodstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_payment_method_id", sa.String(length=255), nullable=False),
        sa.Column("card_brand", sa.String(length=32), nullable=False),
        sa.Column("card_last4", sa.String(length=4), nullable=False),
        sa.Column("expiry_month", sa.Integer(), nullable=False),
        sa.Column("expiry_year", sa.Integer(), nullable=False),
        sa.Column(
            "billing_profile_type",
            sa.Enum("personal", "business", name="billingprofiletype", native_enum=False),
            nullable=False,
        ),
        sa.Column("billing_details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_payment_methods_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_methods")),
        sa.UniqueConstraint(
            "owner_id", "provider", "provider_payment_method_id", name="provider_reference"
        ),
    )
    op.create_index(
        op.f("ix_payment_methods_owner_id"), "payment_methods", ["owner_id"], unique=False
    )
    op.create_table(
        "agent_payment_methods",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_payment_methods_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_agent_payment_methods_payment_method_id_payment_methods"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "agent_id", "payment_method_id", name=op.f("pk_agent_payment_methods")
        ),
    )
    op.create_table(
        "purchase_credentials",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("encrypted_password", sa.Text(), nullable=False),
        sa.Column("login_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_purchase_credentials_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_purchase_credentials_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_credentials")),
    )
    op.create_index(
        op.f("ix_purchase_credentials_agent_id"), "purchase_credentials", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_credentials_owner_id"), "purchase_credentials", ["owner_id"], unique=False
    )
    op.create_table(
        "cart_items",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("selected_payment_method_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("product_url", sa.Text(), nullable=False),
        sa.Column("merchant", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "billing_period",
            sa.Enum("monthly", "yearly", name="billingperiod", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "approved",
                "cancelled",
                "purchased",
                name="cartitemstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_cart_items_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["purchase_credentials.id"],
            name=op.f("fk_cart_items_credential_id_purchase_credentials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_cart_items_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["selected_payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_cart_items_selected_payment_method_id_payment_methods"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("credential_id", name=op.f("uq_cart_items_credential_id")),
    )
    op.create_index(op.f("ix_cart_items_agent_id"), "cart_items", ["agent_id"], unique=False)
    op.create_index(op.f("ix_cart_items_owner_id"), "cart_items", ["owner_id"], unique=False)
    op.create_index(
        "ix_cart_items_owner_status", "cart_items", ["owner_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_cart_items_selected_payment_method_id"),
        "cart_items",
        ["selected_payment_method_id"],
        unique=False,
    )
    op.create_index(op.f("ix_cart_items_status"), "cart_items", ["status"], unique=False)
    op.create_table(
        "purchases",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=False),
        sa.Column("cart_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("completed", "failed", "refunded", name="purchasestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=False),
        sa.Column("receipt_url", sa.Text(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_purchases_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cart_item_id"],
            ["cart_items.id"],
            name=op.f("fk_purchases_cart_item_id_cart_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_purchases_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_purchases_payment_method_id_payment_methods"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
        sa.UniqueConstraint("cart_item_id", name=op.f("uq_purchases_cart_item_id")),
        sa.UniqueConstraint(
            "payment_method_id", "provider_reference", name="payment_provider_reference"
        ),
    )
    op.create_index(op.f("ix_purchases_agent_id"), "purchases", ["agent_id"], unique=False)
    op.create_index(op.f("ix_purchases_owner_id"), "purchases", ["owner_id"], unique=False)
    op.create_index(
        "ix_purchases_owner_purchased_at", "purchases", ["owner_id", "purchased_at"], unique=False
    )
    op.create_index(
        op.f("ix_purchases_payment_method_id"), "purchases", ["payment_method_id"], unique=False
    )
    op.create_index(op.f("ix_purchases_status"), "purchases", ["status"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_id", sa.Uuid(), nullable=False),
        sa.Column(
            "billing_period",
            sa.Enum("monthly", "yearly", name="billingperiod", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "cancelled", "paused", name="subscriptionstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("next_billing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_subscriptions_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_subscriptions_purchase_id_purchases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("purchase_id", name=op.f("uq_subscriptions_purchase_id")),
    )
    op.create_index(op.f("ix_subscriptions_agent_id"), "subscriptions", ["agent_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_owner_id"), "subscriptions", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_owner_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_agent_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_purchases_status"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_payment_method_id"), table_name="purchases")
    op.drop_index("ix_purchases_owner_purchased_at", table_name="purchases")
    op.drop_index(op.f("ix_purchases_owner_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_agent_id"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_cart_items_status"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_selected_payment_method_id"), table_name="cart_items")
    op.drop_index("ix_cart_items_owner_status", table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_owner_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_agent_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_purchase_credentials_owner_id"), table_name="purchase_credentials")
    op.drop_index(op.f("ix_purchase_credentials_agent_id"), table_name="purchase_credentials")
    op.drop_table("purchase_credentials")
    op.drop_table("agent_payment_methods")
    op.drop_index(op.f("ix_payment_methods_owner_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    op.drop_index(op.f("ix_agents_pairing_token_hash"), table_name="agents")
    op.drop_index(op.f("ix_agents_owner_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_api_key_hash"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
